# Generated by Django 3.1 on 2020-10-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='upload',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
