# Generated by Django 3.1 on 2020-10-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_editdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='editdate',
            field=models.DateTimeField(verbose_name='date edited'),
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(verbose_name='date created')),
                ('deletedate', models.DateTimeField(verbose_name='date deleted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.user')),
            ],
        ),
    ]
