# Generated by Django 3.1 on 2020-10-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20201022_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='editdate',
            field=models.DateTimeField(blank=True, verbose_name='date edited'),
        ),
    ]
